<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Hilke.Ant.Plus" />
    <InternalsVisibleTo Include="Hilke.Ant.Testing" />
    <InternalsVisibleTo Include="Hilke.Ant.Tests" />
  </ItemGroup>
</Project>
